import type { Metadata } from "next";
import { Share_Tech_Mono } from "next/font/google";
import "./globals.scss";

const shareTechMono = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Socii Cybernetici",
  description: "Generated by the Catholic Diocese of Discord",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={shareTechMono.className}>
        {children}
      </body>
    </html>
  );
}
